import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SessoinWrapper from "@/components/SessoinWrapper";
import { connection } from "next/server";
import { ThemeProvider } from "@/components/kit/themeProvider";
import StoreWrapper from "@/components/StoreWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppInsfont = Poppins({
  variable: "--font-popp-ins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Home | Next Ecom",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connection();
  return (
    <html lang="en" data-scroll-behavior="smooth" suppressHydrationWarning>
      <SessoinWrapper>
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${poppInsfont.variable} ${poppInsfont.className} antialiased flex flex-col min-h-screen scroll-smooth`}
        >
          <StoreWrapper>
            <ThemeProvider>
              <Navbar />
              <main className="flex-1 background-image">{children}</main>
              <Footer />
            </ThemeProvider>
          </StoreWrapper>
        </body>
      </SessoinWrapper>
    </html>
  );
}
